# Generated by Django 6.0 on 2025-12-09 23:59

import django.db.models.deletion
import parser_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=parser_app.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('original_filename', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ParseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_index', models.IntegerField(default=0)),
                ('pruned_result', models.TextField()),
                ('markdown_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parser_app.imageupload')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
