# Generated by Django 6.0 on 2025-12-10 00:41

import django.db.models.deletion
import django.utils.timezone
import parser_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imageupload',
            options={'ordering': ['-upload_time'], 'verbose_name': '图片上传记录', 'verbose_name_plural': '图片上传记录'},
        ),
        migrations.AlterModelOptions(
            name='parseresult',
            options={'ordering': ['-created_at'], 'verbose_name': '解析结果', 'verbose_name_plural': '解析结果'},
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='imageupload',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='错误信息'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='file_size',
            field=models.BigIntegerField(default='1', help_text='字节', verbose_name='文件大小'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageupload',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='processing_time',
            field=models.FloatField(blank=True, null=True, verbose_name='处理时间(秒)'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='status',
            field=models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上传时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageupload',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='用户代理'),
        ),
        migrations.AddField(
            model_name='parseresult',
            name='output_images_count',
            field=models.IntegerField(default=0, verbose_name='输出图片数量'),
        ),
        migrations.AddField(
            model_name='parseresult',
            name='raw_data',
            field=models.JSONField(blank=True, null=True, verbose_name='原始数据'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='image',
            field=models.ImageField(upload_to=parser_app.models.user_directory_path, verbose_name='图片文件'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='original_filename',
            field=models.CharField(max_length=255, verbose_name='原始文件名'),
        ),
        migrations.AlterField(
            model_name='parseresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='parseresult',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='parser_app.imageupload', verbose_name='原始图片'),
        ),
        migrations.AlterField(
            model_name='parseresult',
            name='markdown_text',
            field=models.TextField(verbose_name='Markdown内容'),
        ),
        migrations.AlterField(
            model_name='parseresult',
            name='pruned_result',
            field=models.TextField(verbose_name='精简结果'),
        ),
        migrations.AlterField(
            model_name='parseresult',
            name='result_index',
            field=models.IntegerField(default=0, verbose_name='结果索引'),
        ),
        migrations.AlterUniqueTogether(
            name='parseresult',
            unique_together={('image', 'result_index')},
        ),
    ]
