# Generated by Django 6.0 on 2025-12-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_alter_imageupload_options_alter_parseresult_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parseresult',
            name='output_images_count',
        ),
        migrations.AddField(
            model_name='parseresult',
            name='markdown_image_paths',
            field=models.JSONField(default=list, verbose_name='Markdown图片路径'),
        ),
        migrations.AddField(
            model_name='parseresult',
            name='output_image_paths',
            field=models.JSONField(default=list, verbose_name='输出图片路径'),
        ),
    ]
